FROM osrf/ubuntu_armhf:focal

# Upgrade existing packages

RUN /bin/bash -c "set -ex; \
    apt-get update; \
    apt-get upgrade -y"

# Copy source

WORKDIR /usr/src/workspace

COPY . /usr/src/workspace/src/stsl

# Install ROS

RUN /bin/bash -c "set -ex; \
    cd src/stsl/deployment/package_generation; \
    ./build_ros_armhf.sh"

# Install package generation utils

RUN /bin/bash -c "set -ex; \
    apt-get install --no-install-recommends -y python3-colcon-common-extensions python3-bloom fakeroot dpkg-dev debhelper"

# Run package generation script

RUN /bin/bash -c "set -ex; \
    source /opt/ros/foxy/setup.bash; \
    rosdep init; \
    rosdep update --rosdistro=foxy; \
    rosdep install --from-paths . --ignore-src -y --skip-keys=\"libgpiod2 libgpiod-dev\"; \
    cd src/stsl/deployment/package_generation; \
    ./generate_debs_internal.sh"
