FROM ros:humble

# Upgrade existing packages

RUN /bin/bash -c "set -ex; \
    apt-get update; \
    apt-get upgrade -y"

# Install package generation utils

RUN /bin/bash -c "set -ex; \
    apt-get install --no-install-recommends -y python3-bloom fakeroot dpkg-dev debhelper"

# Copy source

WORKDIR /usr/src/workspace

COPY . /usr/src/workspace/src/stsl

# Run package generation script

RUN /bin/bash -c "set -ex; \
    source /opt/ros/humble/setup.bash; \
    rosdep update --rosdistro=humble; \
    rosdep install --from-paths . --ignore-src -y --skip-keys=\"libgpiod2 libgpiod-dev\"; \
    cd src/stsl/deployment/package_generation; \
    ./generate_debs_internal.sh"
