#! /bin/bash

set -e

PACKAGING_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$PACKAGING_DIR"

if [ ! -d "../cross_compilation/cross_compile_ws/install_armhf" ]
then
  echo -e "\e[1m\e[31ERROR:\e[0m Could not find the install_armhf directory generated by the cross cross_compilation step."
  echo -e "PLease make sure you have run the cross_compilation step successfully before packaging."
  exit 1
fi

mkdir -p ros2

cp -r ../cross_compilation/cross_compile_ws/install_armhf ros2/

mv ros2/install_armhf ros2/eloquent

tar -czf stsl_package.tar.gz ros2/ robojacketsstsl.service.in

echo -e "\n\n\e[32m\e[1mPackaging Complete!\e[0m"
echo -e "To install on a robot:"
echo -e "Copy stsl_package.tar.gz and install_stsl.sh to the home directory of"
echo -e "the beaglebone, and run install_stsl.sh on the beaglebone.\n"
