name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  buildAndTest:
    runs-on: ubuntu-22.04
    container: ros:humble
    steps:
      - uses: actions/checkout@v2
        with:
          path: src/stsl
      # TODO(barulicm) remove these extra checkouts when nav2 is released
      - uses: actions/checkout@v2
        with:
          path: src/navigation2
          repository: ros-planning/navigation2
          ref: 1.1.0
      - uses: actions/checkout@v2
        with:
          path: src/slam_toolbox
          repository: SteveMacenski/slam_toolbox
          ref: 2.6.0
      # End temporary checkouts
      - name: Install Dependencies
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          sudo apt-get update
          rosdep update --rosdistro=humble
          rosdep install --from-paths . --ignore-src -y --skip-keys="libgpiod2 libgpiod-dev"
      - name: Build
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --packages-skip traini_onboard_interface
      - name: Test
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --packages-skip traini_onboard_interface
          colcon test-result --verbose 
