name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  buildAndTest:
    runs-on: ubuntu-20.04
    container: ros:foxy
    steps:
      - uses: actions/checkout@v2
        with:
          path: src/stsl
      - name: Install Dependencies
        run: |
          . /opt/ros/foxy/setup.bash
          sudo apt-get update
          rosdep update --rosdistro=foxy
          rosdep install --from-paths . --ignore-src -y --skip-keys="libgpiod2 libgpiod-dev"
      - name: Build
        run: |
          . /opt/ros/foxy/setup.bash
          colcon build
      - name: Test
        run: |
          . /opt/ros/foxy/setup.bash
          colcon test
          colcon test-result --verbose
