name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  buildAndTest:
    runs-on: ubuntu-20.04
    steps:
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: foxy
      - uses: actions/checkout@v2
        with:
          path: src/stsl
      - name: Install Dependencies
        run: |
          source /opt/ros/foxy/setup.bash
          rosdep update
          sudo rosdep install -iy --from-paths src
      - name: Build
        run: |
          source /opt/ros/foxy/setup.bash
          colcon build
      - name: Test
        run: |
          source /opt/ros/foxy/setup.bash
          colcon test
          colcon test-result --verbose
