name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  buildAndTest:
    runs-on: ubuntu-20.04
    steps:
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: foxy
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: foxy
